config:
  registries:
  - name: ECR
    api_url: https://385892239032.dkr.ecr.us-east-1.amazonaws.com
    prefix: 385892239032.dkr.ecr.us-east-1.amazonaws.com
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh
    credsexpire: 11h

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |   # notice script name matches above    
      #!/bin/sh
      aws ecr --region us-east-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::385892239032:role/testing-argocd-image-updater-irsa-role
  name: "argocd-image-updater"
